### PR TITLE
Add extensions-Field to GraphQLError.kt

### LINKED ISSUE #165: Add Support for GraphQLError-Extension data
The GraphQL spec states:
> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.
see https://spec.graphql.org/June2018/#example-90475

This should be implmeneted into this project as well.

### PR DESCRIPTION
**Pull request by MaaxGr**
Fixes #165

### CODE REVIEW

**Comment by jeggy** [comment]
Hi @MaaxGr

This looks great! 
Could you write a unit test that validates that your implementation also works?

_Sorry for this late response._

**Comment by MaaxGr** [comment]
Haha. Yeah of course. Hopefully that also doesn't have to wait for some months :D Let's see, when I have time for that

**Comment by MaaxGr** [comment]
Hey. I have added a unit test to verify the serialize()-Method with `extensions`-Object included.

But to be honest i now realize that the implementation doesn't exactly matches the spec.
> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.
https://spec.graphql.org/June2018/#example-90475

This example shows that there can also be substructures in one extension, which is currently not supported in my implementation.
https://www.apollographql.com/docs/apollo-server/data/errors/

How sould we deal with this?

**Comment by MaaxGr** [comment]
Closing this, as we probably should go with MR #171.

**Pull request closed without merging**
