### PR TITLE
Kotlin1.4

### PR DESCRIPTION
**Pull request by inaiat**
bump libs to kotlin 1.4 
convert kotlin serialization code

### CODE REVIEW

**Review by jeggy — APPROVED** [review]
Looks great :+1: 
Thanks!

**Comment by jeggy** [comment]
Could you update to the latest and fix any conflicts, then I will merge it over

**Comment by jeggy** [comment]
Ah, I see now that the conflicts are there because you have targeted my 1.4 branch.
Please just ignore this branch and target the master branch instead, then we will get it merged :+1:

**Comment by inaiat** [comment]
> Ah, I see now that the conflicts are there because you have targeted my 1.4 branch.
> Please just ignore this branch and target the master branch instead, then we will get it merged

Done!

**Comment by jeggy** [comment]
This has been released in version 0.16.0

**Pull request merged**
